//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvertisementId { get; set; }
        public string AdvertisementUserEmail { get; set; }
        public string AdvertisementText { get; set; }
        public Nullable<System.DateTime> AdvertisementTimestamp { get; set; }
    }
}
