//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTopX
    {
        public int ArticleTopXId { get; set; }
        public Nullable<int> TopXOrder { get; set; }
        public string TopXTitle { get; set; }
        public string TopXContent { get; set; }
        public string TopXImage { get; set; }
        public string TopXVideo { get; set; }
        public Nullable<int> ArticleId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
