//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> CommentUserId { get; set; }
        public Nullable<int> CommentPostId { get; set; }
        public Nullable<System.DateTime> CommentCreationDate { get; set; }
    
        public virtual RWSUser RWSUser { get; set; }
    }
}
