//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public Competition()
        {
            this.RWSUsers = new HashSet<RWSUser>();
            this.Teams = new HashSet<Team>();
        }
    
        public int CompetitionId { get; set; }
        public string CompetitionName { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string CompetitionIcon { get; set; }
        public bool isActive { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<RWSUser> RWSUsers { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
