//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngagementType
    {
        public EngagementType()
        {
            this.Engagements = new HashSet<Engagement>();
        }
    
        public int EngTypeId { get; set; }
        public string EngType { get; set; }
        public Nullable<double> EngWeight { get; set; }
    
        public virtual ICollection<Engagement> Engagements { get; set; }
        public virtual EngagementType EngagementType1 { get; set; }
        public virtual EngagementType EngagementType2 { get; set; }
    }
}
