//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int ImageId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
