//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public bool isActive { get; set; }
        public string PlayerIcon { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
    }
}
