//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int PointId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> PointTimestamp { get; set; }
        public Nullable<int> PointTypeId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual RWSUser RWSUser { get; set; }
        public virtual PointType PointType { get; set; }
    }
}
