//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointType
    {
        public PointType()
        {
            this.Points = new HashSet<Point>();
        }
    
        public int PointTypeId { get; set; }
        public string PointTypeName { get; set; }
        public Nullable<double> PointTypeWeight { get; set; }
    
        public virtual ICollection<Point> Points { get; set; }
    }
}
