//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Competitions = new HashSet<Competition>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
        public string RegionIcon { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Competition> Competitions { get; set; }
    }
}
