//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RWS_DevelopmentEntities : DbContext
    {
        public RWS_DevelopmentEntities()
            : base("name=RWS_DevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ArticleTopX> ArticleTopXes { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Competition> Competitions { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<PostType> PostTypes { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<RWSProviderUser> RWSProviderUsers { get; set; }
        public DbSet<RWSRole> RWSRoles { get; set; }
        public DbSet<RWSUser> RWSUsers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Engagement> Engagements { get; set; }
        public DbSet<EngagementType> EngagementTypes { get; set; }
        public DbSet<UserPointsView> UserPointsViews { get; set; }
        public DbSet<TagType> TagTypes { get; set; }
    }
}
