//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWSProviderUser
    {
        public int ID { get; set; }
        public string Provider { get; set; }
        public string ProviderUserId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual RWSUser RWSUser { get; set; }
    }
}
