//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestion
    {
        public int SuggestionId { get; set; }
        public string SuggestionUserEmail { get; set; }
        public string SuggestionText { get; set; }
        public Nullable<System.DateTime> SuggestionTimestamp { get; set; }
    }
}
