//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Images = new HashSet<Image>();
            this.Posts = new HashSet<Post>();
        }
    
        public int TagId { get; set; }
        public string TagName { get; set; }
        public bool isFeatured { get; set; }
        public Nullable<int> TagType { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> TagTypeId { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
