//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.RWSUsers = new HashSet<RWSUser>();
            this.Competitions = new HashSet<Competition>();
            this.Players = new HashSet<Player>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamIcon { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<RWSUser> RWSUsers { get; set; }
        public virtual ICollection<Competition> Competitions { get; set; }
        public virtual ICollection<Player> Players { get; set; }
    }
}
