//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWSDataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPointsView
    {
        public int UserId { get; set; }
        public int PostId { get; set; }
        public Nullable<double> EngWeight { get; set; }
        public Nullable<System.DateTime> EngTimestamp { get; set; }
    }
}
